# Imagem base do .NET SDK para build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia csproj e restaura dependências
COPY *.sln .
COPY WebFamilyHome/*.csproj WebFamilyHome/
RUN dotnet restore

# Copia todo o código e compila
COPY . .
WORKDIR /src/WebFamilyHome
RUN dotnet publish -c Release -o /app/publish

# Imagem base do runtime para execução
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "WebFamilyHome.dll"]
